name = "AssociatedTests"
uuid = "e00e7eca-deca-4415-9dc4-9b3efe792c16"
authors = ["Owen Lynch <root@owenlynch.org>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = "1.0"
